---
- hosts: all
  tasks:
    - name: Include vars
      ansible.builtin.include_vars:
        file: vars/vars.yaml
        name: vars
    - name: test debug
      ansible.builtin.debug:
        msg:
        - "{{vars.vars.user_password|string}}"
        - "{{vars.vars.user_password|string |password_hash('sha512')}}"
    - name: Create user user
      user:
        name: user
        password: "{{vars.vars.user_password|string|password_hash('sha512')}}"
        shell: /bin/bash
        update_password: on_create
      register: user
    - name: sudo user
      command: "usermod -aG sudo user"
    - name: sudo sdadsuser
      shell: "echo {{vars.vars.user_password|string}} > /root/yest"
    - name: sudo sdadsusersad
      shell: "echo asdfasdas >> /root/yest"
#    - name: Force user to change password
#      shell: chage -d 0 user
#      when: user.changed
    - name: Creates .ssh directory
      file:
        path: /home/user/.ssh
        state: directory
    - name: Copying ssh key
      command: "cp /root/.ssh/authorized_keys /home/user/.ssh/authorized_keys"
    - name: setup ssh key permission
      file:
        dest: /home/user/.ssh/authorized_keys
        owner: user
        group: user
        mode: "600"
