---
- hosts: all
  become: true
  tasks:
    - name: apt update
      apt: update_cache=yes
      #command: sudo apt update

    - name: Install Nginx
      apt: name=nginx state=latest

    - name: Disable nginx default site
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: "absent"

    - name: Restart nginx
      service: name=nginx state=restarted

