---
- hosts: all
  tasks:
    - name: Include vars of stuff.yaml into the 'stuff' variable (2.2).
      ansible.builtin.include_vars:
        file: vars/vars.yaml
        name: vars
    - name: tsest debugg
      ansible.builtin.debug:
        msg:
        - "{{ vars['vars']['gamer_password'] }}"
    - name: test debug
      ansible.builtin.debug:
        msg:
        - "{{ vars }}"
        - "{{ vars['gamer_password'] }}"
        - "{{ vars['vars']['gamer_password']  | password_hash('sha512') }}"
    - name: test debugg
      ansible.builtin.debug:
        msg:
        - "{{ gamer_password }}"
