---
- hosts: all
  become: true
  vars:
    php_version: 8.0
  tasks:
    - name: apt update
      apt: update_cache=yes
      #command: sudo apt update

    - name: Install Apache2
      apt: name=apache2 state=latest

    - name: Disable 000-default
      command: a2dissite 000-default.conf

    - name: Listen only 8080
      shell: echo "Listen 8080" > /etc/apache2/ports.conf
    
    - name: Restart apache2
      service: name=apache2 state=restarted

