---
- hosts: all
  become: true
  vars:
    php_version: 8.0
    php_modules:
      - mysql
      - pgsql
      - curl
      - mbstring
      - xml
      - zip
      - gd
    php_fpm_pools:
      - name: blog
        pm_max_children: 10
        pm_start_servers: 4
        pm_min_spare_servers: 2
        pm_max_spare_servers: 6
    php_fpm_ini_options:
      - { option: post_max_size, value: 100M }
      - { option: upload_max_filesize, value: 100M }
      - { section: opcache, option: opcache.enable, value: 1 }
      - { option: max_execution_time, value: 1000 }
      - { option: max_input_time, value: 10000 }
      - { option: max_input_vars, value: 10000 }
      - { option: memory_limit, value: 128M }
      - { option: post_max_size, value: 12M }
      - { option: session.gc_maxlifetime, value: 1440 }
      - { option: upload_max_filesize, value: 40M }
  tasks:
    - name: Install software-properties-common
      apt:
        name:
          - "software-properties-common"
      tags: php-fpm.install

    - name: add ppa:ondrej/php source
      apt_repository:
        validate_certs: no
        repo: 'ppa:ondrej/php'
        state: present

    - name: Update apt cache
      apt: update_cache=yes cache_valid_time=3600

    - name: Install PHP-FPM
      apt:
        name:
          - "php{{ php_version }}-fpm"
      tags: php-fpm.install

    - name: Install PHP modules
      apt:
        name: "php{{ php_version }}-{{ item }}"
      with_items: "{{ php_modules }}"
      tags: php-fpm.install

    - name: Set PHP options for FPM
      ini_file:
        path: /etc/php/{{ php_version }}/fpm/php.ini
        section: "{{ item.section | default('PHP') }}"
        option: "{{ item.option }}"
        value: "{{ item.value }}"
        state: "{{ item.state | default('present') }}"
      with_items: "{{ php_fpm_ini_options }}"
      tags: php-fpm.options

    - name: Enable and start PHP-FPM service
      systemd:
        name: "php{{ php_version }}-fpm.service"
        enabled: true
        state: started
      tags: php-fpm.install

    - name: restart php fpm
      command: sudo service php{{ php_version }}-fpm restart

