---
- hosts: all
  tasks:
    - name: Include vars
      ansible.builtin.include_vars:
        file: vars/vars.yaml
        name: vars
    - name: test debug
      ansible.builtin.debug:
        msg:
        - "{{vars.vars.gamer_password|string}}"
        - "{{vars.vars.gamer_password|string |password_hash('sha512')}}"
    - name: Create gamer user
      user:
        name: gamer
        password: "{{vars.vars.gamer_password|string|password_hash('sha512')}}"
        shell: /bin/bash
        update_password: on_create
      register: gamer
    - name: sudo gamer
      command: "usermod -aG sudo gamer"
    - name: Creates .ssh directory
      file:
        path: /home/gamer/.ssh
        state: directory
    - name: Copying ssh key
      command: "cp /root/.ssh/authorized_keys /home/gamer/.ssh/authorized_keys"
    - name: setup ssh key permission
      file:
        dest: /home/gamer/.ssh/authorized_keys
        owner: gamer
        group: gamer
        mode: "600"
